server:
    port: 8081
spring:
    application:
        name: otp-service-1
    redis:
        host: localhost
        port: 6379
        username: alliano-dev
        password: alliano361
        connect-timeout: 10s
        database: 0
    jpa:
        database: redis
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/
logging:
  level:
    jap:
        microservice:
            account-service: debug
